name: test_Git_project
description: ''
version: 0.0.1
author: karunkumarbussari@gmail.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: testgitproject
  parentArtefactID: karunkumarbussarigmailcomteam
  buildSystem: maven
  author: null
  createdAt: '2024-08-13 17:16:12'
pipelines:
  pipelines/Test_Git_Pipeline:
    name: Test_Git_Pipeline
    description: ''
    author: karunkumarbussari@gmail.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-08-13 17:16:12'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-13 17:16:12'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-13T17:16:12.937614Z'
  name: plibMaven
  version: 8.0.31
  id: '686720055'
  createdAt: '2024-08-13T17:16:12.937614Z'
  type: plibMaven
projectDependencies:
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-08-13 17:15:35'
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.5.5
    isDefault: true
    author: null
    createdAt: '2024-08-13 17:15:35'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
